# https://taskfile.dev
version: '3'

tasks:
  default:
    cmds:
      - task: install
      - task: cov

  tidy:
    cmds:
     - go mod tidy
     - go mod vendor

  install:
    cmds:
      - task: tidy
      - go install

  ci-test:
    cmds:
      - go run ci/main.go

  ci-cov:
    cmds:
      - go run ci/main.go --cover

  test:
    cmds:
      - go test ./...

  cov:
    cmds:
      - go test ./... --cover
